server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://82.157.70.24:3306/CITEL_T_003?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8&allowMultiQueries=true&autoReconnect=true
    username: root
    password: xly666888666
#开启日志
mybatis-plus:
  type-aliases-package: cn.edu.bjtu.citel.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl